export { default as ComingSoon } from "./comingsoon/ComingSoon";
export { default as Footer } from "./footer/Footer";
export { default as Navbar } from "./navbar/Navbar";
export { default as DemoPage } from "./demopage/DemoPage";
export { default as TextDemo } from "./textdemo/TextDemo";
export { default as SoundDemo } from "./SoundDemo";
export { default as BackgroundOne } from "./BackgroundOne";
export { default as Loading } from "./Loading";
export { default as ArtGallery } from "./ArtGallery";
